<a href="https://colab.research.google.com/github/warwavn/AIMLKMITL2024/blob/Day3/Day3/01_Tokenizer/Models_Tokenizers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

runpod.io >> cloud service MI300x

In [1]:


import IPython
import sys

def clean_notebook():
    IPython.display.clear_output(wait=True)
    print("Notebook cleaned.")

!pip install bitsandbytes
#!pip install transformers


# Clean up the notebook
clean_notebook()

Notebook cleaned.


In [2]:
from transformers import AutoTokenizer

In [3]:
checkpoint = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

# Tokenizer

In [4]:
tokenizer

BertTokenizerFast(name_or_path='bert-base-uncased', vocab_size=30522, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}

In [5]:
tokenizer("hello world")

{'input_ids': [101, 7592, 2088, 102], 'token_type_ids': [0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1]}

In [6]:
tokens = tokenizer.tokenize("hello world")
tokens

['hello', 'world']

In [7]:
ids = tokenizer.convert_tokens_to_ids(tokens)
ids

[7592, 2088]

In [ ]:
tokenizer.decode(ids)

'hello world'

In [ ]:
txt = "wrong txt"
ids = tokenizer.encode(txt)
ids

In [ ]:
ids = tokenizer.encode("hello world")
ids

[101, 7592, 2088, 102]

In [ ]:
tokenizer.convert_ids_to_tokens(ids)

['[CLS]', 'hello', 'world', '[SEP]']

In [ ]:
tokenizer.decode(ids)

'[CLS] hello world [SEP]'

# Play with model with 2 classes

In [10]:
from transformers import AutoModelForSequenceClassification

checkpoint = "bert-base-uncased"
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [11]:
model

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e

out ออกกี่
pytorch, tensorflow 3 >> need to config
hg +fn, optimizer

In [12]:
model_inputs = tokenizer("hello world", return_tensors='pt')
model_inputs

{'input_ids': tensor([[ 101, 7592, 2088,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1]])}

In [ ]:
# the default was to create a binary classifier!
outputs = model(**model_inputs)
outputs

SequenceClassifierOutput(loss=None, logits=tensor([[0.2286, 0.3630]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

** mapping dict

In [ ]:
data = [
  "I like cats.",
  "Do you like cats too?",
]
tokenizer(data)

{'input_ids': [[101, 1045, 2066, 8870, 1012, 102], [101, 2079, 2017, 2066, 8870, 2205, 1029, 102]], 'token_type_ids': [[0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1]]}

# how to apply with 3 class

In [ ]:
checkpoint = "bert-base-uncased"
model = AutoModelForSequenceClassification.from_pretrained(checkpoint, num_labels=3)
model

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12,

In [ ]:
outputs = model(**model_inputs)
outputs

SequenceClassifierOutput(loss=None, logits=tensor([[ 0.0302,  0.1894, -0.3282]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [ ]:
outputs['logits']

tensor([[ 0.0302,  0.1894, -0.3282]], grad_fn=<AddmmBackward0>)

# Multi inputs and outputs





* The [CLS] token is used as the first token of every sequence. It stands for "classification" and is used in tasks where a single representation of the entire sequence is needed, such as sentence classification. The output corresponding to this token from the model's hidden states is typically used as the aggregate representation of the sequence.
[SEP] (Separator Token):

* The [SEP] token is used to separate different segments (sentences) within a sequence. It is particularly useful in tasks that involve pairs of sentences, such as question-answering or sentence-pair classification. It indicates the boundary between segments.
[PAD] (Padding Token):

* The [PAD] token is used to pad sequences to a uniform length. In a batch of sequences, this ensures that all sequences have the same length, which is required for efficient processing in deep learning models. Padding is typically added at the end of the sequence

```
['[CLS] i like cats. [SEP] [PAD] [PAD]', '[CLS] do you like cats too? [SEP]']
```


In the first sequence, [CLS] i like cats. [SEP] [PAD] [PAD]:

* [CLS] marks the beginning of the sequence.
* [SEP] indicates the end of the sentence.
* [PAD] [PAD] pads the sequence to a uniform length with the second sequence.

In the second sequence, [CLS] do you like cats too? [SEP]:

* [CLS] marks the beginning of the sequence.
* [SEP] indicates the end of the sentence.
* No padding is required since the sequence length is sufficient.





In [ ]:
data = [
  "I like cats.",
  "Do you like cats too?",
]
model_inputs = tokenizer(data, padding=True, truncation=True, return_tensors='pt')

model_inputs

{'input_ids': tensor([[ 101, 1045, 2066, 8870, 1012,  102,    0,    0],
        [ 101, 2079, 2017, 2066, 8870, 2205, 1029,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1]])}

In [ ]:
data

['I like cats.', 'Do you like cats too?']

In [ ]:
model_inputs['attention_mask']

tensor([[1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
model_inputs['input_ids']

tensor([[ 101, 1045, 2066, 8870, 1012,  102,    0,    0],
        [ 101, 2079, 2017, 2066, 8870, 2205, 1029,  102]])

skip_special_tokens=True
exclude special char

In [ ]:

decoded_texts = tokenizer.batch_decode(model_inputs['input_ids'], skip_special_tokens=True)
decoded_texts

['i like cats.', 'do you like cats too?']

In [ ]:
decoded_texts = tokenizer.batch_decode(model_inputs['input_ids'], skip_special_tokens=False)
decoded_texts

['[CLS] i like cats. [SEP] [PAD] [PAD]', '[CLS] do you like cats too? [SEP]']

In [ ]:
outputs = model(**model_inputs)
outputs

SequenceClassifierOutput(loss=None, logits=tensor([[ 0.2925,  0.1846, -0.1072],
        [ 0.2621,  0.1767, -0.1195]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [ ]:
outputs['logits']

tensor([[ 0.2925,  0.1846, -0.1072],
        [ 0.2621,  0.1767, -0.1195]], grad_fn=<AddmmBackward0>)

# Example of Full System for Text Generation

GPT2 provide both tokenizer and model
GPT3+ only tokenizer

In [ ]:
from transformers import GPT2LMHeadModel, GPT2Tokenizer, BitsAndBytesConfig


# Load pre-trained model and tokenizer with quantization
model = GPT2LMHeadModel.from_pretrained('gpt2')
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [ ]:
# Encode the input text
input_text = "The quick brown fox"
input_ids = tokenizer.encode(input_text, return_tensors='pt')
input_ids

tensor([[  464,  2068,  7586, 21831]])

# Generate Text

In [ ]:
# Generate text
output = model.generate(input_ids, max_length=128,pad_token_id=tokenizer.eos_token_id)

output

tensor([[  464,  2068,  7586, 21831,   274,   389,   257,  1049,   835,   284,
           651,   257,  1310,  1643,   286,   257,  4829,   503,   286,   534,
          3290,    13,   198,   198,   464,  2068,  7586, 21831,   274,   389,
           257,  1049,   835,   284,   651,   257,  1310,  1643,   286,   257,
          4829,   503,   286,   534,  3290,    13,   383,  2068,  7586, 21831,
           274,   389,   257,  1049,   835,   284,   651,   257,  1310,  1643,
           286,   257,  4829,   503,   286,   534,  3290,    13,   383,  2068,
          7586, 21831,   274,   389,   257,  1049,   835,   284,   651,   257,
          1310,  1643,   286,   257,  4829,   503,   286,   534,  3290,    13,
           383,  2068,  7586, 21831,   274,   389,   257,  1049,   835,   284,
           651,   257,  1310,  1643,   286,   257,  4829,   503,   286,   534,
          3290,    13,   383,  2068,  7586, 21831,   274,   389,   257,  1049,
           835,   284,   651,   257,  1310,  1643,  

In [ ]:
test = output[0][7:10]
test

tensor([1049,  835,  284])

In [ ]:
tokenizer.decode(test)

' great way to'

In [ ]:
# Decode the output
generated_texts = [tokenizer.decode(output[i], skip_special_tokens=True) for i in range(len(output))]
generated_texts

['The quick brown foxes are a great way to get a little bit of a kick out of your dog.\n\nThe quick brown foxes are a great way to get a little bit of a kick out of your dog. The quick brown foxes are a great way to get a little bit of a kick out of your dog. The quick brown foxes are a great way to get a little bit of a kick out of your dog. The quick brown foxes are a great way to get a little bit of a kick out of your dog. The quick brown foxes are a great way to get a little bit of a']